services:
  - type: web
    name: bun-auth-backend
    runtime: docker
    rootDir: bun-auth
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_MAX_CONNECTIONS
        value: 10
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: BETTER_AUTH_URL
        sync: false
      - key: FRONTEND_URL
        value: https://77mdiasdev.vercel.app
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
    buildCommand: bun install
    startCommand: bun run src/index.ts
    healthCheckPath: /
    autoDeploy: true
